input AccountRecord {
  _id: String
  value: Int
}

type AccountResponse {
  serialNumber: String
  deleted: Boolean
  balance: Int
  updatedAt: String
  createdAt: String
}

# type Query {
# }

type Mutation {
  accountAddCredit(record: AccountRecord): AccountResponse
}
